language: python
python:
  - "3.6"
notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - TO_TEST=CODE
    - TO_TEST=NOTEBOOKS
    - TO_TEST=STYLE
    - TO_TEST=BROWSER

install:
  - pip install -e .
  - pip install pytest-cov codecov mypy flake8 nose
  - if [ "$TO_TEST" = "NOTEBOOKS" ]; then pip install notebook nbconvert; fi
  - if [ "$TO_TEST" = "BROWSER" ]; then pip install notebook; fi
  - if [ "$TO_TEST" = "BROWSER" ]; then npm install -g casperjs; fi
  - if [ "$TO_TEST" = "BROWSER" ]; then wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi
  - if [ "$TO_TEST" = "BROWSER" ]; then tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2; fi

script:
  - if [ "$TO_TEST" = "CODE" ]; then mypy -p cornerstone_widget --ignore-missing-imports; fi
  - if [ "$TO_TEST" = "CODE" ]; then pytest --cov=cornerstone_widget; fi
  - if [ "$TO_TEST" = "CODE" ]; then codecov; fi
  - if [ "$TO_TEST" = "STYLE" ]; then flake8 --ignore E501,F401; fi
  - if [ "$TO_TEST" = "NOTEBOOKS" ]; then source build_tools/travis_notebooks.sh; fi
  - if [ "$TO_TEST" = "BROWSER" ]; then source build_tools/travis_browser.sh; fi
